// Generated by CoffeeScript 1.3.1
(function() {
  var location, match, regex;

  if (!localStorage.django_version) {
    localStorage.django_version = '1.6';
  }

  $(function() {
    return $('ul#doc-versions a').click(function() {
      return localStorage.django_version = $(this).html();
    });
  });

  regex = new RegExp("docs.djangoproject.com/[^/]*/([^/]*)");

  match = regex.exec(window.location);

  if (match && match[1] !== localStorage.django_version) {
    location = String(window.location);
    window.location = location.replace(match[1], localStorage.django_version);
  }

}).call(this);
