// Generated by CoffeeScript 1.3.1
(function() {
  var match, new_url_string, regex, url_string;

  if (!localStorage.django_version) {
    localStorage.django_version = '1.6';
  }

  $(function() {
    return $('ul#doc-versions a').click(function() {
      return localStorage.django_version = $(this).html();
    });
  });

  regex = new RegExp("docs.djangoproject.com/[^/]*/([^/]*)");

  match = regex.exec(window.location);

  if (match && match[1] !== localStorage.django_version) {
    url_string = window.location.href;
    new_url_string = url_string.replace(match[1], localStorage.django_version);
    window.location.replace(new_url_string);
  }

}).call(this);
