// Generated by CoffeeScript 1.6.3
(function() {
  var display_msg, match, new_url_string, regex, url_string;

  if (!localStorage.django_version) {
    localStorage.django_version = '1.11';
  }

  $(document).ready(function() {
    return $('ul#doc-versions a').click(function() {
      return localStorage.django_version = $(this).html();
    });
  });

  regex = new RegExp("docs.djangoproject.com/[^/]*/([0-9]+\.[0-9]+|dev)/");

  match = regex.exec(window.location);

  if (match && match[1] !== localStorage.django_version) {
    url_string = window.location.href;
    new_url_string = url_string.replace(match[1], localStorage.django_version);
    window.location.replace(new_url_string);
    localStorage.display_version_switcher_message = true;
  } else if (localStorage.display_version_switcher_message) {
    delete localStorage.display_version_switcher_message;
    display_msg = function() {
      var $message_div, hide_msg;
      $message_div = $("<div class='version-switcher-message'><p>You've been redirected to the docs for <strong>" + localStorage.django_version + "</strong>.&nbsp;&nbsp;<em>- Django Docs Version Switcher</em</p></div>");
      $message_div.appendTo(document.body);
      hide_msg = function() {
        return $message_div.fadeOut();
      };
      return setTimeout(hide_msg, 5000);
    };
    $(document).ready(display_msg);
  }

}).call(this);
